---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/public_html/register
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R register/dist/renderer/* $DEPLOYPATH/
    - /bin/cp register/dist/renderer/.htaccess $DEPLOYPATH/

