---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/register.crestcyber.co.ke
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R register/dist/renderer/* $DEPLOYPATH/
    - /bin/cp register/dist/renderer/.htaccess $DEPLOYPATH/


